version: '3.1'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: backend
    ports:
      - '5000:5000'
    stdin_open: true
    tty: true
    networks:
      - app-network

  frontend:
    container_name: frontend
    restart: always
    build:
      context: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - 'backend'

  nginx:
    depends_on:
      - frontend
    restart: always
    build:
      context: nginx
    ports:
      - '80:80'
networks:
  app-network:
